; MocciaCAN — Waveshare ESP32-S3-Touch-LCD-7 (ESP32-S3-N16R8)
; Compilar:        pio run
; Subir firmware:  pio run -t upload
; Subir web:       pio run -t uploadfs   (contenido de data/ -> LittleFS)
; Monitor serie:   pio device monitor    (UART0 vía el puerto USB-UART; el USB nativo
;                  queda desconectado porque USB_SEL=1 enruta GPIO19/20 al transceptor CAN)

[platformio]
default_envs = moccia

[env:moccia]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino

; --- Memoria: 16 MB flash QIO + 8 MB PSRAM OPI ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv   ; app0/app1 6.25 MB + spiffs(LittleFS) 3.4 MB
board_build.filesystem = littlefs

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
    -DCONFIG_ASYNC_TCP_STACK_SIZE=12288
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -DWS_MAX_QUEUED_MESSAGES=24
    -Wall
    -Wno-unused-function

lib_deps =
    lovyan03/LovyanGFX@1.1.16
    mathieucarbou/AsyncTCP@3.3.2
    mathieucarbou/ESPAsyncWebServer@3.6.0
    bblanchon/ArduinoJson@^7.2.0
